version: 2

jobs:
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack build

  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run: cargo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
