version: 2

jobs:
  build_wasm:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install wasm-pack
          command: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run:
          name: Build wasm
          command: wasm-pack build

  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Run tests
          command: cargo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_wasm
      - test
